server:
  port: 9899
spring:
  application:
    name: jobnotification
  datasource:
    url: jdbc:mysql://localhost:3306/jobnotification
    username: root
    password: surya
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true